# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('rating_list', models.TextField()),
                ('person_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_rated', to='users.Person')),
                ('person_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person')),
            ],
        ),
    ]
